import { CuisineSeed } from "./interfaces";

export const cuisines: CuisineSeed[] = [
	{ name: "Chinese" },
	{ name: "Thai" },
	{ name: "Indian" },
	{ name: "Korean" },
	{ name: "Japanese" },
	{ name: "Mexican" },
	{ name: "Jamaican" },
	{ name: "Cajun" },
	{ name: "Italian" },
	{ name: "Vegan/Vegetarian" },
	{ name: "Carribean" },
	{ name: "Soul Food" },
	{ name: "Vietnamese" },
	{ name: "French" },
	{ name: "Middle Eastern" },
	{ name: "Moroccan" },
	{ name: "Greek" },
	{ name: "Lebanese" },
	{ name: "Mediterranean" },
	{ name: "Tex-Mex" },
	{ name: "American" },
	{ name: "Seafood" },
	{ name: "British" },
	{ name: "Filipino" },
	{ name: "African" },
];
