import { IngredientSeed } from "./interfaces";

export const ingredients: IngredientSeed[] = [
	{ name: "Angelica" },
	{ name: "Savoy cabbage" },
	{ name: "Silver linden" },
	{ name: "Gochuchang" },
	{ name: "Kiwi" },
	{ name: "Allium" },
	{ name: "Dark Soy Sauce" },
	{ name: "Light Soy Sauce" },
	{ name: "Garden onion" },
	{ name: "Leek" },
	{ name: "Garlic Clove" },
	{ name: "Chives" },
	{ name: "Lemon verbena" },
	{ name: "Cashew nut" },
	{ name: "Pineapple" },
	{ name: "Dill" },
	{ name: "Custard apple" },
	{ name: "Wild celery" },
	{ name: "Peanut" },
	{ name: "Burdock" },
	{ name: "Horseradish" },
	{ name: "Tarragon" },
	{ name: "Mugwort" },
	{ name: "Asparagus" },
	{ name: "Oat" },
	{ name: "Star fruit" },
	{ name: "Brazil nut" },
	{ name: "Common beet" },
	{ name: "Borage" },
	{ name: "Chinese mustard" },
	{ name: "Swede" },
	{ name: "Rape" },
	{ name: "Common cabbage" },
	{ name: "Cauliflower" },
	{ name: "Brussel sprouts" },
	{ name: "Kohlrabi" },
	{ name: "Broccoli" },
	{ name: "Chinese cabbage" },
	{ name: "Turnip" },
	{ name: "Pigeon pea" },
	{ name: "Tea" },
	{ name: "Capers" },
	{ name: "Pepper" },
	{ name: "Papaya" },
	{ name: "Safflower" },
	{ name: "Caraway" },
	{ name: "Pecan nut" },
	{ name: "Chestnut" },
	{ name: "Roman camomile" },
	{ name: "Chickpea" },
	{ name: "Endive" },
	{ name: "Chicory" },
	{ name: "Chinese cinnamon" },
	{ name: "Ceylon cinnamon" },
	{ name: "Watermelon" },
	{ name: "Lime" },
	{ name: "Lemon" },
	{ name: "Pummelo" },
	{ name: "Mandarin orange (Clementine Tangerine)" },
	{ name: "Sweet orange" },
	{ name: "Coffee" },
	{ name: "Arabica coffee" },
	{ name: "Robusta coffee" },
	{ name: "Coriander" },
	{ name: "Common hazelnut" },
	{ name: "Saffron" },
	{ name: "Muskmelon" },
	{ name: "Cucumber" },
	{ name: "Cucurbita" },
	{ name: "Cumin" },
	{ name: "Turmeric" },
	{ name: "Quince" },
	{ name: "Lemon grass" },
	{ name: "Globe artichoke" },
	{ name: "Wild carrot" },
	{ name: "Japanese persimmon" },
	{ name: "Cardamom" },
	{ name: "Black crowberry" },
	{ name: "Loquat" },
	{ name: "Rocket salad (ssp.)" },
	{ name: "Wax apple" },
	{ name: "Common buckwheat" },
	{ name: "Tartary buckwheat" },
	{ name: "Fig" },
	{ name: "Fennel" },
	{ name: "Strawberry" },
	{ name: "Black huckleberry" },
	{ name: "Soy bean" },
	{ name: "Sunflower" },
	{ name: "Sea-buckthornberry" },
	{ name: "Barley" },
	{ name: "Hyssop" },
	{ name: "Star anise" },
	{ name: "Swamp cabbage" },
	{ name: "Sweet potato" },
	{ name: "Black walnut" },
	{ name: "Common walnut" },
	{ name: "Lettuce" },
	{ name: "Grass pea" },
	{ name: "Sweet bay" },
	{ name: "Lentils" },
	{ name: "Garden cress" },
	{ name: "Lovage" },
	{ name: "Flaxseed" },
	{ name: "Mexican oregano" },
	{ name: "Lichee" },
	{ name: "Lupine" },
	{ name: "Apple" },
	{ name: "Mango" },
	{ name: "German camomile" },
	{ name: "Lemon balm" },
	{ name: "Mentha" },
	{ name: "Orange mint" },
	{ name: "Cornmint" },
	{ name: "Cornstarch" },
	{ name: "Spearmint" },
	{ name: "Peppermint" },
	{ name: "Medlar" },
	{ name: "Bitter gourd" },
	{ name: "Mulberry" },
	{ name: "Black mulberry" },
	{ name: "Nutmeg" },
	{ name: "Sweet basil" },
	{ name: "Evening primrose" },
	{ name: "Olive" },
	{ name: "Sweet marjoram" },
	{ name: "Pot marjoram" },
	{ name: "Common oregano" },
	{ name: "Rice" },
	{ name: "Millet" },
	{ name: "Poppy" },
	{ name: "Passion fruit" },
	{ name: "Parsnip" },
	{ name: "Avocado" },
	{ name: "Parsley" },
	{ name: "Scarlet bean" },
	{ name: "Lima bean" },
	{ name: "Common bean" },
	{ name: "Date" },
	{ name: "Black chokeberry" },
	{ name: "Anise" },
	{ name: "Pine nut" },
	{ name: "Pepper (Spice)" },
	{ name: "Pistachio" },
	{ name: "Common pea" },
	{ name: "Purslane" },
	{ name: "Prunus (Cherry Plum)" },
	{ name: "Apricot" },
	{ name: "Sweet cherry" },
	{ name: "Sour cherry" },
	{ name: "European plum" },
	{ name: "Almond" },
	{ name: "Peach" },
	{ name: "Guava" },
	{ name: "Pomegranate" },
	{ name: "Pear" },
	{ name: "Radish" },
	{ name: "Garden rhubarb" },
	{ name: "Blackcurrant" },
	{ name: "Redcurrant" },
	{ name: "Gooseberry" },
	{ name: "Watercress" },
	{ name: "Rosemary" },
	{ name: "Rubus" },
	{ name: "Cloudberry" },
	{ name: "Red raspberry" },
	{ name: "Black raspberry" },
	{ name: "Sorrel" },
	{ name: "Common sage" },
	{ name: "Black elderberry" },
	{ name: "Summer savory" },
	{ name: "Winter savory" },
	{ name: "Rye" },
	{ name: "Sesame" },
	{ name: "Garden tomato" },
	{ name: "Cherry tomato" },
	{ name: "Garden tomato (var.)" },
	{ name: "Eggplant" },
	{ name: "Potato" },
	{ name: "Rowanberry" },
	{ name: "Sorghum" },
	{ name: "Spinach" },
	{ name: "Cloves" },
	{ name: "Tamarind" },
	{ name: "Dandelion" },
	{ name: "Cocoa bean" },
	{ name: "Common thyme" },
	{ name: "Linden" },
	{ name: "Small-leaf linden" },
	{ name: "Fenugreek" },
	{ name: "Common wheat" },
	{ name: "Vaccinium" },
	{ name: "Lowbush blueberry" },
	{ name: "Sparkleberry" },
	{ name: "Highbush blueberry" },
	{ name: "American cranberry" },
	{ name: "Bilberry" },
	{ name: "Lingonberry" },
	{ name: "Vanilla" },
	{ name: "Common verbena" },
	{ name: "Broad bean" },
	{ name: "Adzuki bean" },
	{ name: "Gram bean" },
	{ name: "Mung bean" },
	{ name: "Climbing bean" },
	{ name: "Cowpea" },
	{ name: "Muscadine grape" },
	{ name: "Common grape" },
	{ name: "Corn" },
	{ name: "Ginger" },
	{ name: "Arctic blackberry" },
	{ name: "Banana" },
	{ name: "Bayberry" },
	{ name: "Elliott's blueberry" },
	{ name: "Canada blueberry" },
	{ name: "Bog bilberry" },
	{ name: "Buffalo currant" },
	{ name: "Celeriac" },
	{ name: "Celery stalks" },
	{ name: "Chinese chives" },
	{ name: "European cranberry" },
	{ name: "Deerberry" },
	{ name: "Ginseng" },
	{ name: "Cascade huckleberry" },
	{ name: "Oval-leaf huckleberry" },
	{ name: "Evergreen huckleberry" },
	{ name: "Red huckleberry" },
	{ name: "Longan" },
	{ name: "Macadamia nut (M. tetraphylla)" },
	{ name: "Garden onion (var.)" },
	{ name: "Summer grape" },
	{ name: "Fox grape" },
	{ name: "Nectarine" },
	{ name: "Peach (var.)" },
	{ name: "Pepper (C. baccatum)" },
	{ name: "Pepper (C. chinense)" },
	{ name: "Pepper (Capsicum)" },
	{ name: "Rambutan" },
	{ name: "Red rice" },
	{ name: "Annual wild rice" },
	{ name: "Swiss chard" },
	{ name: "Lemon thyme" },
	{ name: "Tronchuda cabbage" },
	{ name: "Japanese walnut" },
	{ name: "Welsh onion" },
	{ name: "Hard wheat" },
	{ name: "Shallot" },
	{ name: "Rocket salad" },
	{ name: "Carrot" },
	{ name: "Triticale" },
	{ name: "Black cabbage" },
	{ name: "Half-highbush blueberry" },
	{ name: "Celery leaves" },
	{ name: "Chicory leaves" },
	{ name: "Komatsuna" },
	{ name: "Pak choy" },
	{ name: "Napa cabbage" },
	{ name: "Chicory roots" },
	{ name: "Grapefruit/Pummelo hybrid" },
	{ name: "Grapefruit" },
	{ name: "Jostaberry" },
	{ name: "Kai-lan" },
	{ name: "Italian oregano" },
	{ name: "Oxheart cabbage" },
	{ name: "Daikon radish" },
	{ name: "Black radish" },
	{ name: "Radish (var.)" },
	{ name: "Red beetroot" },
	{ name: "Sweet rowanberry" },
	{ name: "Pineappple sage" },
	{ name: "Skunk currant" },
	{ name: "Beer" },
	{ name: "Other bread" },
	{ name: "Breakfast cereal" },
	{ name: "Other soy product" },
	{ name: "Other cereal product" },
	{ name: "Pasta" },
	{ name: "Biscuit" },
	{ name: "Sourdough" },
	{ name: "Spirit" },
	{ name: "Fortified wine" },
	{ name: "Other alcoholic beverage" },
	{ name: "Abalone" },
	{ name: "Abiyuch" },
	{ name: "Acerola" },
	{ name: "Acorn" },
	{ name: "Winter squash" },
	{ name: "Agar" },
	{ name: "Red king crab" },
	{ name: "Alfalfa" },
	{ name: "Allspice" },
	{ name: "Amaranth" },
	{ name: "Arrowhead" },
	{ name: "Arrowroot" },
	{ name: "Asian pear" },
	{ name: "Atlantic herring" },
	{ name: "Atlantic mackerel" },
	{ name: "Painted comber" },
	{ name: "Atlantic pollock" },
	{ name: "Atlantic wolffish" },
	{ name: "Bamboo shoots" },
	{ name: "Striped bass" },
	{ name: "Beech nut" },
	{ name: "Beluga whale" },
	{ name: "Bison" },
	{ name: "Alaska blackfish" },
	{ name: "Blue crab" },
	{ name: "Blue mussel" },
	{ name: "Northern bluefin tuna" },
	{ name: "Bluefish" },
	{ name: "Wild boar" },
	{ name: "Bowhead whale" },
	{ name: "Breadfruit" },
	{ name: "Breadnut tree seed" },
	{ name: "Rapini" },
	{ name: "Buffalo" },
	{ name: "Burbot" },
	{ name: "Giant butterbur" },
	{ name: "American butterfish" },
	{ name: "Butternut" },
	{ name: "Butternut squash" },
	{ name: "Calabash" },
	{ name: "Cardoon" },
	{ name: "Natal plum" },
	{ name: "Carob" },
	{ name: "Common carp" },
	{ name: "Cassava" },
	{ name: "Channel catfish" },
	{ name: "Chayote" },
	{ name: "Cherimoya" },
	{ name: "Chervil" },
	{ name: "Chia" },
	{ name: "Chicken" },
	{ name: "Chicken Stock" },
	{ name: "Boneless Chicken Thigh" },
	{ name: "Chicken Thigh" },
	{ name: "Chinese broccoli" },
	{ name: "Chinese chestnut" },
	{ name: "Chinese water chestnut" },
	{ name: "Garland chrysanthemum" },
	{ name: "Cisco" },
	{ name: "Nuttall cockle" },
	{ name: "Coconut" },
	{ name: "Pacific cod" },
	{ name: "Atlantic cod" },
	{ name: "Common octopus" },
	{ name: "Corn salad" },
	{ name: "Cottonseed" },
	{ name: "Catjang pea" },
	{ name: "Malus (Crab apple)" },
	{ name: "Squashberry" },
	{ name: "Atlantic croaker" },
	{ name: "Cusk" },
	{ name: "Cuttlefish" },
	{ name: "Mule deer" },
	{ name: "Devilfish" },
	{ name: "Dock" },
	{ name: "Dolphin fish" },
	{ name: "Freshwater drum" },
	{ name: "Mallard duck" },
	{ name: "Dungeness crab" },
	{ name: "Durian" },
	{ name: "Eastern oyster" },
	{ name: "Freshwater eel" },
	{ name: "Elderberry" },
	{ name: "Elk" },
	{ name: "Emu" },
	{ name: "Oregon yampah" },
	{ name: "European anchovy" },
	{ name: "European chestnut" },
	{ name: "Turbot" },
	{ name: "Fireweed" },
	{ name: "Florida pompano" },
	{ name: "Ginkgo nuts" },
	{ name: "Greylag goose" },
	{ name: "Grape" },
	{ name: "Greenland halibut/turbot" },
	{ name: "Groundcherry" },
	{ name: "Grouper" },
	{ name: "Guinea hen" },
	{ name: "Haddock" },
	{ name: "Hippoglossus (Common halibut)" },
	{ name: "Hazelnut" },
	{ name: "Hickory nut" },
	{ name: "Horse" },
	{ name: "Horseradish tree" },
	{ name: "Alaska blueberry" },
	{ name: "Hyacinth bean" },
	{ name: "Irish moss" },
	{ name: "Pacific jack mackerel" },
	{ name: "Jackfruit" },
	{ name: "Japanese chestnut" },
	{ name: "Java plum" },
	{ name: "Jerusalem artichoke" },
	{ name: "Jujube" },
	{ name: "Jute" },
	{ name: "Kale" },
	{ name: "Kelp" },
	{ name: "King mackerel" },
	{ name: "Kumquat" },
	{ name: "Lambsquarters" },
	{ name: "Leather chiton" },
	{ name: "Wild leek" },
	{ name: "Common ling" },
	{ name: "Lingcod" },
	{ name: "American lobster" },
	{ name: "Loganberry" },
	{ name: "Lotus" },
	{ name: "Sacred lotus" },
	{ name: "White lupine" },
	{ name: "Malabar spinach" },
	{ name: "Mammee apple" },
	{ name: "Purple mangosteen" },
	{ name: "Alpine sweetvetch" },
	{ name: "Milkfish" },
	{ name: "Monkfish" },
	{ name: "Moth bean" },
	{ name: "Mountain yam" },
	{ name: "Striped mullet" },
	{ name: "White mustard" },
	{ name: "Mustard spinach" },
	{ name: "New Zealand spinach" },
	{ name: "Nopal" },
	{ name: "Ocean pout" },
	{ name: "North Pacific giant octopus" },
	{ name: "Ohelo berry" },
	{ name: "Okra" },
	{ name: "Tunicate" },
	{ name: "Ostrich" },
	{ name: "Spotted seal" },
	{ name: "Pacific herring" },
	{ name: "Pacific oyster" },
	{ name: "Pacific rockfish" },
	{ name: "Velvet duck" },
	{ name: "Pepper (C. frutescens)" },
	{ name: "Common persimmon" },
	{ name: "Pheasant" },
	{ name: "Northern pike" },
	{ name: "Pili nut" },
	{ name: "Colorado pinyon" },
	{ name: "Pitanga" },
	{ name: "Plains prickly pear" },
	{ name: "French plantain" },
	{ name: "American pokeweed" },
	{ name: "Opium poppy" },
	{ name: "Prairie turnip" },
	{ name: "Prickly pear" },
	{ name: "Quinoa" },
	{ name: "European rabbit" },
	{ name: "Rainbow smelt" },
	{ name: "Rainbow trout" },
	{ name: "Malabar plum" },
	{ name: "Rose hip" },
	{ name: "Roselle" },
	{ name: "Orange roughy" },
	{ name: "Sablefish" },
	{ name: "Pink salmon" },
	{ name: "Chum salmon" },
	{ name: "Coho salmon" },
	{ name: "Sockeye salmon" },
	{ name: "Chinook salmon" },
	{ name: "Atlantic salmon" },
	{ name: "Salmonberry" },
	{ name: "Common salsify" },
	{ name: "Sapodilla" },
	{ name: "Mamey sapote" },
	{ name: "Spanish mackerel" },
	{ name: "Pacific sardine" },
	{ name: "Scallop" },
	{ name: "Scup" },
	{ name: "Sea cucumber" },
	{ name: "Steller sea lion" },
	{ name: "Bearded seal" },
	{ name: "Ringed seal" },
	{ name: "Sea trout" },
	{ name: "Sesbania flower" },
	{ name: "American shad" },
	{ name: "Shark" },
	{ name: "Sheefish" },
	{ name: "Lamb" },
	{ name: "Sheepshead" },
	{ name: "Hedge mustard" },
	{ name: "Skipjack tuna" },
	{ name: "Snapper" },
	{ name: "Soursop" },
	{ name: "Spelt" },
	{ name: "Spirulina" },
	{ name: "Squab" },
	{ name: "Strawberry guava" },
	{ name: "Greater sturgeon" },
	{ name: "White sucker" },
	{ name: "Sugar apple" },
	{ name: "Pumpkinseed sunfish" },
	{ name: "Swordfish" },
	{ name: "Taro" },
	{ name: "Teff" },
	{ name: "Tilefish" },
	{ name: "Mexican groundcherry" },
	{ name: "Towel gourd" },
	{ name: "Salmonidae" },
	{ name: "Turkey" },
	{ name: "Cattle (Veal)" },
	{ name: "Walleye" },
	{ name: "Alaska pollock" },
	{ name: "Wasabi" },
	{ name: "Wax gourd" },
	{ name: "Whelk" },
	{ name: "Coalfish pollock" },
	{ name: "Broad whitefish" },
	{ name: "Whitefish" },
	{ name: "Whiting" },
	{ name: "Wild rice" },
	{ name: "Tea leaf willow" },
	{ name: "Winged bean" },
	{ name: "Yam" },
	{ name: "Jicama" },
	{ name: "Yautia" },
	{ name: "Yellowfin tuna" },
	{ name: "Yellowtail amberjack" },
	{ name: "Pollock" },
	{ name: "Albacore tuna" },
	{ name: "Gadus (Common cod)" },
	{ name: "Atlantic halibut" },
	{ name: "Pacific halibut" },
	{ name: "Pacific salmon" },
	{ name: "Smelt" },
	{ name: "Clupeinae" },
	{ name: "Spiny lobster" },
	{ name: "Snow crab" },
	{ name: "Black-eyed pea" },
	{ name: "Deer" },
	{ name: "Macadamia nut" },
	{ name: "Percoidei (Bass and others)" },
	{ name: "Perciformes" },
	{ name: "Rabbit" },
	{ name: "Domestic goat" },
	{ name: "Beefalo" },
	{ name: "Bivalvia" },
	{ name: "Squid" },
	{ name: "Shrimp" },
	{ name: "Crayfish" },
	{ name: "Flatfish" },
	{ name: "Domestic pig" },
	{ name: "Walrus" },
	{ name: "Alaska wild rhubarb" },
	{ name: "Oriental wheat" },
	{ name: "Yardlong bean" },
	{ name: "Quail" },
	{ name: "Boysenberry" },
	{ name: "Persian lime" },
	{ name: "Feijoa" },
	{ name: "Rowal" },
	{ name: "Jew's ear" },
	{ name: "Common mushroom" },
	{ name: "Shiitake" },
	{ name: "Purple laver" },
	{ name: "Wakame" },
	{ name: "Enokitake" },
	{ name: "Epazote" },
	{ name: "Oyster mushroom" },
	{ name: "Cloud ear fungus" },
	{ name: "Maitake" },
	{ name: "Ostrich fern" },
	{ name: "Spot croaker" },
	{ name: "Sourdock" },
	{ name: "Tinda" },
	{ name: "Atlantic menhaden" },
	{ name: "Wheat" },
	{ name: "Common chokecherry" },
	{ name: "Agave" },
	{ name: "Narrowleaf cattail" },
	{ name: "Jellyfish" },
	{ name: "Anchovy" },
	{ name: "Blue whiting" },
	{ name: "Carp bream" },
	{ name: "Chanterelle" },
	{ name: "Sturgeon" },
	{ name: "Charr" },
	{ name: "Cinnamon" },
	{ name: "Crab" },
	{ name: "Common dab" },
	{ name: "Spiny dogfish" },
	{ name: "Anatidae" },
	{ name: "Anguilliformes" },
	{ name: "True frog" },
	{ name: "Garfish" },
	{ name: "Gadiformes" },
	{ name: "Mountain hare" },
	{ name: "Lake trout" },
	{ name: "Lemon sole" },
	{ name: "Clawed lobster" },
	{ name: "Lumpsucker" },
	{ name: "Scombridae" },
	{ name: "Marine mussel" },
	{ name: "Norway haddock" },
	{ name: "Norway lobster" },
	{ name: "Norway pout" },
	{ name: "Oil palm" },
	{ name: "True oyster" },
	{ name: "Sago palm" },
	{ name: "Persimmon" },
	{ name: "Pikeperch" },
	{ name: "Pleuronectidae" },
	{ name: "Rock ptarmigan" },
	{ name: "Pacific ocean perch" },
	{ name: "Black salsify" },
	{ name: "True seal" },
	{ name: "Red algae" },
	{ name: "Kombu" },
	{ name: "Snail" },
	{ name: "True sole" },
	{ name: "Catfish" },
	{ name: "Thistle" },
	{ name: "Thunnus" },
	{ name: "Walnut" },
	{ name: "Cetacea" },
	{ name: "Columbidae (Dove Pigeon)" },
	{ name: "Conch" },
	{ name: "Grape wine" },
	{ name: "Berry wine" },
	{ name: "Cooking wine" },
	{ name: "Apple cider" },
	{ name: "Liquor" },
	{ name: "Cheese" },
	{ name: "Milk (Cow)" },
	{ name: "Eggs" },
	{ name: "Yogurt" },
	{ name: "Bean" },
	{ name: "Vodka" },
	{ name: "Whisky" },
	{ name: "Ice cream" },
	{ name: "Gin" },
	{ name: "Honey" },
	{ name: "Liquorice" },
	{ name: "Vinegar" },
	{ name: "Rum" },
	{ name: "Port wine" },
	{ name: "Vermouth" },
	{ name: "Sherry" },
	{ name: "Madeira wine" },
	{ name: "Nougat" },
	{ name: "Toffee" },
	{ name: "Cake" },
	{ name: "Pizza" },
	{ name: "Ymer" },
	{ name: "Other snack food" },
	{ name: "Crisp bread" },
	{ name: "Pastry" },
	{ name: "Dragée" },
	{ name: "Chewing gum" },
	{ name: "Marzipan" },
	{ name: "Salad dressing" },
	{ name: "Sauce" },
	{ name: "Salt" },
	{ name: "Butter" },
	{ name: "Butter substitute" },
	{ name: "Cream" },
	{ name: "Sugar" },
	{ name: "Sausage" },
	{ name: "Meatball" },
	{ name: "Mustard" },
	{ name: "Pate" },
	{ name: "Sugar substitute" },
	{ name: "Meat bouillon" },
	{ name: "Whey" },
	{ name: "Casein" },
	{ name: "Fruit preserve" },
	{ name: "Leavening agent" },
	{ name: "Marshmallow" },
	{ name: "Gelatin" },
	{ name: "Water" },
	{ name: "Baby food" },
	{ name: "Dumpling" },
	{ name: "Soup" },
	{ name: "Syrup" },
	{ name: "Tallow" },
	{ name: "Remoulade" },
	{ name: "Chocolate spread" },
	{ name: "Fruit gum" },
	{ name: "Curry powder" },
	{ name: "Other candy" },
	{ name: "Meringue" },
	{ name: "Lard" },
	{ name: "Other animal fat" },
	{ name: "Other cocoa product" },
	{ name: "Cocoa butter" },
	{ name: "Cocoa powder" },
	{ name: "Cocoa liquor" },
	{ name: "Chocolate" },
	{ name: "Hot chocolate" },
	{ name: "Dried milk" },
	{ name: "Milk (Other mammals)" },
	{ name: "Kefir" },
	{ name: "Buttermilk" },
	{ name: "Soy sauce" },
	{ name: "Miso" },
	{ name: "Tofu" },
	{ name: "Zwieback" },
	{ name: "Roe" },
	{ name: "Cichlidae (Tilapia)" },
	{ name: "Icing" },
	{ name: "Snack bar" },
	{ name: "Green turtle" },
	{ name: "Energy drink" },
	{ name: "Burrito" },
	{ name: "Hamburger" },
	{ name: "Baked beans" },
	{ name: "Chili" },
	{ name: "Chili Oil" },
	{ name: "Taco" },
	{ name: "Tortilla" },
	{ name: "Nachos" },
	{ name: "Processed cheese" },
	{ name: "Salad" },
	{ name: "Cream substitute" },
	{ name: "Dulce de leche" },
	{ name: "Topping" },
	{ name: "Sweet custard" },
	{ name: "Egg roll" },
	{ name: "Heart of palm" },
	{ name: "Popcorn" },
	{ name: "Potato chip" },
	{ name: "Tortilla chip" },
	{ name: "Corn chip" },
	{ name: "Hibiscus tea" },
	{ name: "Stew" },
	{ name: "Gelatin dessert" },
	{ name: "Junket" },
	{ name: "Falafel" },
	{ name: "Frybread" },
	{ name: "Other frozen dessert" },
	{ name: "Lasagna" },
	{ name: "Morchella (Morel)" },
	{ name: "Pancake" },
	{ name: "Pectin" },
	{ name: "Pudding" },
	{ name: "Waffle" },
	{ name: "Soy milk" },
	{ name: "Meatloaf" },
	{ name: "Sake" },
	{ name: "Cocktail" },
	{ name: "Couscous" },
	{ name: "Bulgur" },
	{ name: "Coffee substitute" },
	{ name: "Coffee mocha" },
	{ name: "Chimichanga" },
	{ name: "Semolina" },
	{ name: "Tapioca pearl" },
	{ name: "Tostada" },
	{ name: "Quesadilla" },
	{ name: "Baked potato" },
	{ name: "Hot dog" },
	{ name: "Spread" },
	{ name: "Enchilada" },
	{ name: "Egg substitute" },
	{ name: "Nutritional drink" },
	{ name: "Other sandwich" },
	{ name: "Ketchup" },
	{ name: "Breakfast sandwich" },
	{ name: "Adobo" },
	{ name: "Macaroni and cheese" },
	{ name: "Butterfat" },
	{ name: "Horned melon" },
	{ name: "Hushpuppy" },
	{ name: "Fruit juice" },
	{ name: "Relish" },
	{ name: "Other fruit product" },
	{ name: "Fruit salad" },
	{ name: "Soy yogurt" },
	{ name: "Veggie burger" },
	{ name: "Vegetable Oil" },
	{ name: "Cold cut" },
	{ name: "Mixed nuts" },
	{ name: "Canola" },
	{ name: "Babassu palm" },
	{ name: "Cupuaçu" },
	{ name: "Shea tree" },
	{ name: "Oil-seed Camellia" },
	{ name: "Ucuhuba" },
	{ name: "Phyllo dough" },
	{ name: "Cooking oil" },
	{ name: "Pie crust" },
	{ name: "Pie filling" },
	{ name: "Pie" },
	{ name: "Shortening" },
	{ name: "Soy cream" },
	{ name: "Ice cream cone" },
	{ name: "Molasses" },
	{ name: "Cracker" },
	{ name: "Nance" },
	{ name: "Naranjilla" },
	{ name: "Natto" },
	{ name: "Ravioli" },
	{ name: "Scrapple" },
	{ name: "Other pasta dish" },
	{ name: "Succotash" },
	{ name: "Tamale" },
	{ name: "Rice cake" },
	{ name: "Tree fern" },
	{ name: "Evaporated milk" },
	{ name: "Flour" },
	{ name: "Akutaq" },
	{ name: "Dough" },
	{ name: "Pita bread" },
	{ name: "Focaccia" },
	{ name: "Bagel" },
	{ name: "Other bread product" },
	{ name: "Piki bread" },
	{ name: "French toast" },
	{ name: "Wheat bread" },
	{ name: "Rye bread" },
	{ name: "Oat bread" },
	{ name: "Potato bread" },
	{ name: "Cornbread" },
	{ name: "Corn grits" },
	{ name: "Multigrain bread" },
	{ name: "Rice bread" },
	{ name: "Pan dulce" },
	{ name: "Raisin bread" },
	{ name: "Wonton wrapper" },
	{ name: "Trail mix" },
	{ name: "Greenthread tea" },
	{ name: "Fruit-flavor drink" },
	{ name: "Vegetable juice" },
	{ name: "Horchata" },
	{ name: "Soft drink" },
	{ name: "Frozen yogurt" },
	{ name: "Milkshake" },
	{ name: "Chocolate mousse" },
	{ name: "Dripping" },
	{ name: "Pupusa" },
	{ name: "Empanada" },
	{ name: "Arepa" },
	{ name: "Ascidians" },
	{ name: "Gefilte fish" },
	{ name: "Yellow pond-lily" },
	{ name: "Fish burger" },
	{ name: "Other dish" },
	{ name: "Pot pie" },
	{ name: "Stuffing" },
	{ name: "Edible shell" },
	{ name: "Fudge" },
	{ name: "Candy bar" },
	{ name: "Condensed milk" },
	{ name: "Margarine" },
	{ name: "Margarine-like spread" },
	{ name: "Hummus" },
	{ name: "Potato puffs" },
	{ name: "Potato gratin" },
	{ name: "Milk substitute" },
	{ name: "Pepper (C. pubescens)" },
	{ name: "Soft-necked garlic" },
	{ name: "Cabbage" },
	{ name: "Chinese bayberry" },
	{ name: "Mushrooms" },
	{ name: "Pomes" },
	{ name: "Brassicas" },
	{ name: "Citrus" },
	{ name: "Crustaceans" },
	{ name: "Fats and oils" },
	{ name: "Fishes" },
	{ name: "Pulses" },
	{ name: "Mollusks" },
	{ name: "Nuts" },
	{ name: "Fruits" },
	{ name: "Sunburst squash (pattypan squash)" },
	{ name: "Green zucchini" },
	{ name: "Yellow zucchini" },
	{ name: "Green bell pepper" },
	{ name: "Yellow bell pepper" },
	{ name: "Orange bell pepper" },
	{ name: "Red bell pepper" },
	{ name: "Italian sweet red pepper" },
	{ name: "Yellow wax bean" },
	{ name: "Green bean" },
	{ name: "Saskatoon berry" },
	{ name: "Nanking cherry" },
	{ name: "Japanese pumpkin" },
	{ name: "White cabbage" },
	{ name: "Romaine lettuce" },
	{ name: "Castanospermum australe" },
	{ name: "Gentiana lutea" },
	{ name: "Juniperus communis" },
	{ name: "Albizia gummifera" },
	{ name: "Mundu" },
	{ name: "Rabbiteye blueberry" },
	{ name: "Yali pear" },
	{ name: "Asparagus racemosus" },
	{ name: "Evergreen blackberry" },
	{ name: "Asparagus fern" },
	{ name: "Thornless blackberry" },
	{ name: "Tropical highland blackberry" },
	{ name: "Andean blackberry" },
	{ name: "Blackberry" },
	{ name: "Black tea" },
	{ name: "Green tea" },
	{ name: "Olive oil" },
	{ name: "Macroalgae" },
	{ name: "Red wine" },
	{ name: "linseed oil" },
	{ name: "Rapeseed oil" },
	{ name: "Soybean oil" },
	{ name: "Guarana" },
	{ name: "Mate" },
	{ name: "White wine" },
	{ name: "Sour orange" },
	{ name: "Egg yolk" },
	{ name: "Rosé wine" },
	{ name: "White mulberry" },
	{ name: "Canola oil" },
	{ name: "Dessert wine" },
	{ name: "Red champagne" },
	{ name: "Red tea" },
	{ name: "White champagne" },
	{ name: "Red grape juice" },
	{ name: "White grape juice" },
	{ name: "Crosne" },
	{ name: "Red clover" },
	{ name: "Partridge berry" },
	{ name: "Mikan" },
	{ name: "Mozzarella cheese" },
	{ name: "Plain cream cheese" },
	{ name: "Cheddar Cheese" },
	{ name: "Parmesan cheese" },
	{ name: "Almond milk" },
	{ name: "Coconut milk" },
	{ name: "Salted butter" },
	{ name: "Sunflower oil" },
	{ name: "Coconut oil" },
	{ name: "Peanut oil" },
	{ name: "Cottonseed oil" },
	{ name: "Corn oil" },
	{ name: "Avocado oil" },
	{ name: "Grapeseed oil" },
	{ name: "Sesame oil" },
	{ name: "Sesame Seeds" },
	{ name: "Monterey Jack cheese" },
	{ name: "Swiss cheese" },
	{ name: "Cottage cheese" },
	{ name: "Blue cheese" },
	{ name: "Clam" },
	{ name: "Sour cream" },
	{ name: "Whole wheat bread" },
	{ name: "Jalapeno pepper" },
	{ name: "Greek feta cheese" },
	{ name: "Eddoe" },
	{ name: "Plantain" },
	{ name: "Clementine" },
	{ name: "Green apple" },
	{ name: "White onion" },
	{ name: "Red onion" },
	{ name: "Green onion" },
	{ name: "Green grape" },
	{ name: "Red grape" },
	{ name: "Black plum" },
	{ name: "Green cabbage" },
	{ name: "Black raisin" },
	{ name: "Cannellini bean" },
	{ name: "Green lentil" },
	{ name: "Cubanelle pepper" },
	{ name: "Acorn squash" },
	{ name: "Iceberg lettuce" },
	{ name: "Japanese sea bass" },
	{ name: "Pea shoots" },
	{ name: "Yau choy" },
	{ name: "Water spinach" },
	{ name: "Chineese plum" },
	{ name: "Green plum" },
	{ name: "Wampee" },
	{ name: "Pitaya" },
	{ name: "Goji" },
	{ name: "Monk fruit" },
	{ name: "Cantaloupe melon" },
	{ name: "Hawthorn" },
	{ name: "Lantern fruit" },
	{ name: "White bread" },
	{ name: "Cape gooseberry" },
	{ name: "Herbal tea" },
	{ name: "Fish oil" },
	{ name: "Taco shell" },
	{ name: "Tostada shell" },
];
